In [58]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [59]:
import pandas as pd

In [60]:
%cd /content/drive/MyDrive/Colab Notebooks/프로젝트_공공

/content/drive/MyDrive/Colab Notebooks/프로젝트_공공

In [61]:
#날짜별 지하철 승하차 정보 불러오기
sub01 = pd.read_csv('Data/CARD_SUBWAY_MONTH_202101.csv',index_col = False)
sub02 = pd.read_csv('Data/CARD_SUBWAY_MONTH_202102.csv',index_col = False)
sub03 = pd.read_csv('Data/CARD_SUBWAY_MONTH_202103.csv',index_col = False)
sub04 = pd.read_csv('Data/CARD_SUBWAY_MONTH_202104.csv',index_col = False)
sub05 = pd.read_csv('Data/CARD_SUBWAY_MONTH_202105.csv',index_col = False)
sub06 = pd.read_csv('Data/CARD_SUBWAY_MONTH_202106.csv',index_col = False)
sub07 = pd.read_csv('Data/CARD_SUBWAY_MONTH_202107.csv',index_col = False)
sub08 = pd.read_csv('Data/CARD_SUBWAY_MONTH_202108.csv',index_col = False)

In [62]:
#1년 평균 승하차 인원 구하기


#데이터 합치기
sub_sum = pd.concat([sub01,sub02,sub03,sub04,sub05,sub06,sub07,sub08])
#sub_sum

sub_groub = sub_sum.groupby('역명').mean()

sub_mean = sub_groub[['승차총승객수','하차총승객수']]
sub_mean = sub_mean.reset_index()
sub_mean

sub_mean.to_csv

#괄호와 괄호안의 문자 지우기
sub_mean['역명'] = sub_mean['역명'].astype(str).str.replace(r"\(.*\)","")

In [63]:
#구 별 승하차 인원 구하기

subway = pd.read_csv('Data/전국도시철도역사정보표준데이터(작업).csv',encoding='cp949')
subway.head()

#서울이 아닌 역 삭제
subway = subway[subway['역사도로명주소'].str.contains('서울')]


target = subway[subway['역사도로명주소'].str.contains('용산')]

target['역사명']

for n in list(set(target['역사명'])):
  print(n)

서울역
서빙고
한남
삼각지
숙대입구
녹사평
신용산
용산
남영
이촌
효창공원앞
이태원
한강진

In [69]:

sub_name = sub_mean[sub_mean['역명']=='서울역']
sub_name



df2 = pd.DataFrame([[sub_name.iloc[0,1], sub_name.iloc[0,2]]], columns=['승차총승객수', '하차총승객수'])
df2

df = pd.DataFrame(columns=['역명','승차총승객수', '하차총승객수'])
for n in target['역사명']:
  sub_name = sub_mean[sub_mean['역명']==n]
  df2 = pd.DataFrame([[sub_name.iloc[0,0],sub_name.iloc[0,1],sub_name.iloc[0,2]]], columns=['역명','승차총승객수', '하차총승객수'])
  df = df.append(df2)

df

      역명        승차총승객수        하차총승객수
0    서울역  10963.700896  10789.603097
0  효창공원앞   3931.440329   3840.370370
0     남영   7392.292181   7739.325103
0     용산  27811.613169  28065.699588
0     이촌   4575.872428   4573.465021
0    서빙고   1556.098765   1432.860082
0     한남   3355.148148   3170.580247
0    서울역  10963.700896  10789.603097
0   숙대입구  10230.934156  10012.333333
0    삼각지   4337.059671   4228.183128
0    신용산  12210.806584  12886.967078
0     이촌   4575.872428   4573.465021
0  효창공원앞   3931.440329   3840.370370
0    삼각지   4337.059671   4228.183128
0    녹사평   4188.164609   4125.440329
0    이태원   8224.518519   8421.469136
0    한강진   6406.386831   7354.893004

In [65]:
#구 별 승하차 인원 구하기
#name(입력값)으로 구 넣기

def get_subway_pop(name):
  #주소에 구 이름(name)이 포함된 역사를 target에 저장
  target = subway[subway['역사도로명주소'].str.contains(name)]

  #빈 데이터 프레임 생성
  df = pd.DataFrame(columns=['역명','승차총승객수', '하차총승객수'])

  #각 행(각 역)을 for문으로 돌며 빈 데이터 프레임에 해당 역의 승차,하차 승객수 추가
  for n in list(set(target['역사명'])):
    sub_name = sub_mean[sub_mean['역명']==n]
    df2 = pd.DataFrame([[sub_name.iloc[0,0],sub_name.iloc[0,1],sub_name.iloc[0,2]]], columns=['역명','승차총승객수', '하차총승객수'])
    df = df.append(df2)
  return df

In [72]:
#승,하차 인원 더하기
def sum_pop(df):
  Sum = df['승차총승객수'].sum() + df['하차총승객수'].sum()
  #반올림 해서 값 반환
  return round(Sum)



gu_list = ['강남','강동','강서','강북','관악','광진','구로','금천','노원','동대문','도봉','동작','마포','서대문','성동','성북','서초','송파','영등포','용산','양천','은평','종로','중구','중랑']

gu_pop =[]
for gu in gu_list:
  gu_pop.append(sum_pop(get_subway_pop(gu)))

print(gu_pop)

subway_pop = pd.DataFrame({ 'gu_name':gu_list, 'sub_pop':gu_pop })
subway_pop

[807503, 217104, 206906, 125649, 262776, 243426, 329633, 96071, 262848, 167358, 254260, 292030, 284088, 93773, 414160, 149850, 286624, 361603, 312802, 211825, 123023, 225161, 344224, 311710, 156772]

   gu_name  sub_pop
0       강남   807503
1       강동   217104
2       강서   206906
3       강북   125649
4       관악   262776
5       광진   243426
6       구로   329633
7       금천    96071
8       노원   262848
9      동대문   167358
10      도봉   254260
11      동작   292030
12      마포   284088
13     서대문    93773
14      성동   414160
15      성북   149850
16      서초   286624
17      송파   361603
18     영등포   312802
19      용산   211825
20      양천   123023
21      은평   225161
22      종로   344224
23      중구   311710
24      중랑   156772